import type { Metadata } from 'next'
import { Inter, Nunito } from 'next/font/google'
import './globals.css'
import clsx from 'clsx'
import { SessionProvider } from 'next-auth/react'
import { auth } from '@/auth'
import { Header } from '@/components/header'

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })

const nunito = Nunito({ subsets: ['latin'], variable: '--font-nunito' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth()
  return (
    <html lang="en" className={clsx(inter.variable, nunito.variable)}>
      <SessionProvider refetchOnWindowFocus={false} session={session}>
        <body className="min-h-screen min-w-screen">
          <Header />
          <div className="p-4">{children}</div>
        </body>
      </SessionProvider>
    </html>
  )
}
